# Air configuration for auto-reload
# https://github.com/cosmtrek/air

root = "./cmd/auto-rename"
tmp_dir = "tmp"

[cmd]
  bin = "go"
  args = ["run", "main.go", "-cron", "-dir=/tmp"]

[env]
DIR = ".env"

[build]
cmd = "go build -o ./tmp/main cmd/auto-rename/main.go"
bin = "./tmp/main"
args = ["-dir=./tmp"]
