version: '3.8'

services:
  auto-rename:
    container_name: auto-rename
    image: auto-rename
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # Mount your local directory for files to be renamed
      # Set FILES_PATH in .env, default to ./files if not set
      # Mount directory for persistent database storage
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/renames.db
    # Default: Start web server only (access at http://localhost:8080)
    # command: ["-web-only", "-db=/app/data/renames.db", "-web-port=8080"]
    restart: always

    # Alternative commands:
    # For renaming files and then starting web server:
    # command: ["-dir=/app/files", "-db=/app/data/renames.db", "-web-port=8080"]
    # For dry-run mode with web server:
    # command: ["-dir=/app/files", "-dry-run", "-db=/app/data/renames.db", "-web-port=8080"]
    # For renaming files only (no web server):
    # command: ["-dir=/app/files", "-db=/app/data/renames.db"]
